In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

# Adjusting the brightness of the image
(brighter means increase pixel values by some extend and reverse for reducing brightness)

In [2]:
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    cv.imshow("Original",img)
    if cv.waitKey(1)==27:
        cam.release()
        break

In [3]:
img.shape

(480, 640, 3)

In [4]:
img.mean()

np.float64(128.4842241753472)

In [5]:
img

array([[[195, 187, 180],
        [193, 185, 179],
        [191, 183, 177],
        ...,
        [197, 190, 188],
        [196, 189, 186],
        [193, 186, 183]],

       [[204, 196, 189],
        [201, 193, 187],
        [199, 191, 185],
        ...,
        [199, 192, 190],
        [198, 191, 188],
        [194, 187, 184]],

       [[199, 191, 184],
        [197, 189, 182],
        [197, 189, 183],
        ...,
        [199, 193, 190],
        [197, 191, 188],
        [193, 187, 184]],

       ...,

       [[164, 195, 197],
        [161, 191, 193],
        [159, 186, 189],
        ...,
        [ 94, 115, 112],
        [ 98, 119, 116],
        [ 96, 117, 114]],

       [[155, 180, 183],
        [164, 188, 190],
        [174, 197, 199],
        ...,
        [ 97, 118, 115],
        [ 99, 120, 117],
        [ 96, 117, 114]],

       [[192, 214, 216],
        [196, 218, 220],
        [198, 219, 220],
        ...,
        [104, 125, 122],
        [104, 125, 122],
        [103, 124, 121]]

In [6]:
img-20

array([[[175, 167, 160],
        [173, 165, 159],
        [171, 163, 157],
        ...,
        [177, 170, 168],
        [176, 169, 166],
        [173, 166, 163]],

       [[184, 176, 169],
        [181, 173, 167],
        [179, 171, 165],
        ...,
        [179, 172, 170],
        [178, 171, 168],
        [174, 167, 164]],

       [[179, 171, 164],
        [177, 169, 162],
        [177, 169, 163],
        ...,
        [179, 173, 170],
        [177, 171, 168],
        [173, 167, 164]],

       ...,

       [[144, 175, 177],
        [141, 171, 173],
        [139, 166, 169],
        ...,
        [ 74,  95,  92],
        [ 78,  99,  96],
        [ 76,  97,  94]],

       [[135, 160, 163],
        [144, 168, 170],
        [154, 177, 179],
        ...,
        [ 77,  98,  95],
        [ 79, 100,  97],
        [ 76,  97,  94]],

       [[172, 194, 196],
        [176, 198, 200],
        [178, 199, 200],
        ...,
        [ 84, 105, 102],
        [ 84, 105, 102],
        [ 83, 104, 101]]

In [7]:
import cv2 as cv
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    img1=img-100
    cv.imshow("Original",img)
    cv.imshow("Filter_1(img-100)",img1)
    
    if cv.waitKey(1)==27:
        cam.release()
        break

In [8]:
print("Shape of original image",img.shape)
print("Shape of filter image",img1.shape)

Shape of original image (480, 640, 3)
Shape of filter image (480, 640, 3)


In [9]:
print("mean of original image",img.mean())
print("mean of filter image",img1.mean())

mean of original image 123.45103081597222
mean of filter image 128.23519748263888


In [10]:
print("Values of original image",img)
print("Values of filter image",img1)

Values of original image [[[182 179 175]
  [181 179 175]
  [175 173 169]
  ...
  [188 182 179]
  [187 181 178]
  [184 179 176]]

 [[191 188 184]
  [189 187 183]
  [185 183 179]
  ...
  [190 183 180]
  [187 181 178]
  [185 180 177]]

 [[190 187 183]
  [189 187 183]
  [188 186 182]
  ...
  [190 183 180]
  [188 182 179]
  [185 180 177]]

 ...

 [[151 185 185]
  [150 184 184]
  [149 182 182]
  ...
  [ 83 100  97]
  [ 96 113 110]
  [ 97 114 111]]

 [[153 183 182]
  [154 183 183]
  [159 186 186]
  ...
  [ 94 111 108]
  [106 123 120]
  [104 121 118]]

 [[177 204 204]
  [180 206 206]
  [185 209 209]
  ...
  [101 118 115]
  [111 128 125]
  [107 124 121]]]
Values of filter image [[[ 82  79  75]
  [ 81  79  75]
  [ 75  73  69]
  ...
  [ 88  82  79]
  [ 87  81  78]
  [ 84  79  76]]

 [[ 91  88  84]
  [ 89  87  83]
  [ 85  83  79]
  ...
  [ 90  83  80]
  [ 87  81  78]
  [ 85  80  77]]

 [[ 90  87  83]
  [ 89  87  83]
  [ 88  86  82]
  ...
  [ 90  83  80]
  [ 88  82  79]
  [ 85  80  77]]

 ...

 [[ 

# Increasing the brightness of the pixel 

In [ ]:
import cv2 as cv
pixels=float(50)
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    img2=img*1.5
    img2[img2<0]=0
    img2[img2>255]=255
    img2=img2.astype(np.uint8)
    cv.imshow("Original",img)
    cv.imshow("Filter_2(img*1.5)",img2)
    
    if cv.waitKey(1)==27:
        cam.release()
        break

# when i multiply the image with values the brightness will get adjusted in accordance to that.
#when I mutiplied with higher values the entire frame got splitted in colors insted on making it brighter

In [ ]:
print("Shape of original image",img.shape)
print("Shape of filter image",img2.shape)

In [ ]:
print("mean of original image",img.mean())
print("mean of filter image",img2.mean())

In [ ]:
print("Values of original image",img)
print("-"*100)
print("Values of filter image",img2)

# Applying filter

In [ ]:
import cv2 as cv
pixels = float(10)

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img, 1)
    
    img_1 = img + pixels
    img_1[img_1 <  0 ] = 0
    img_1[img_1 > 255] = 255
    img_1 = img_1.astype(np.uint8)
    
    img_2 = img*1.5
    img_2[img_2 <  0 ] = 0
    img_2[img_2 > 255] = 255
    img_2 = img_2.astype(np.uint8)
    
    img_3 = img *2
    img_3[img_3 <  0 ] = 0
    img_3[img_3 > 255] = 255
    img_3 = img_3.astype(np.uint8)
    
    
    cv.imshow("Original",img)
    cv.imshow("Filter-1",img_1)
    cv.imshow("Filter-2",img_2)
    cv.imshow("Filter-3",img_3)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

# Reducing the brightness

In [ ]:
import cv2 as cv
pixels = float(10)

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img, 1)
    
    img_1 = img *0.9
    img_1[img_1 <  0 ] = 0
    img_1[img_1 > 255] = 255
    img_1 = img_1.astype(np.uint8)
    
    img_2 = img *0.7
    img_2[img_2 <  0 ] = 0
    img_2[img_2 > 255] = 255
    img_2 = img_2.astype(np.uint8)
    
    img_3 = img*0.5
    img_3[img_3 <  0 ] = 0
    img_3[img_3 > 255] = 255
    img_3 = img_3.astype(np.uint8)
    
    
    cv.imshow("Original",img)
    cv.imshow("Filter-1",img_1)
    cv.imshow("Filter-2",img_2)
    cv.imshow("Filter-3",img_3)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break