In [1]:
#harcascade is a face detection file in which all facial fetaures are mentioned. copywrite- Intel

In [2]:
import cv2 as cv
import numpy as np


In [3]:
classifier=cv.CascadeClassifier("haarcascade_frontalface_default.xml")
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    faces=classifier.detectMultiScale(img,1.1,8)
    cv.imshow("Frame",img)
    print(faces)
    print('-'*20)
    if cv.waitKey(1)==27:
        cam.release()
        break

[[166 123 170 170]]
--------------------
[[172 122 163 163]]
--------------------
[[169 120 168 168]]
--------------------
[[169 120 166 166]]
--------------------
[[168 119 167 167]]
--------------------
[[169 119 166 166]]
--------------------
[[168 119 168 168]]
--------------------
[[166 118 174 174]]
--------------------
[[167 117 172 172]]
--------------------
[[166 117 170 170]]
--------------------
[[163 116 176 176]]
--------------------
[[152 114 181 181]]
--------------------
[[149 114 183 183]]
--------------------
[[148 113 183 183]]
--------------------
[[148 112 186 186]]
--------------------
[[139 113 188 188]]
--------------------
[[138 113 189 189]]
--------------------
[[137 116 171 171]]
--------------------
[[135 115 171 171]]
--------------------
[[134 112 175 175]]
--------------------
[[134 112 175 175]]
--------------------
[[136 115 171 171]]
--------------------
[[137 115 187 187]]
--------------------
[[140 117 184 184]]
--------------------
[[142 120 179 17

 the 4 values represent- coordinates of the face(top-left x axis,top-left y axis,width,height of frame)

In [4]:
classifier=cv.CascadeClassifier("haarcascade_frontalface_default.xml")
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    faces=classifier.detectMultiScale(img,2,2)#img,confidence,neighbours(higher the confidence less faces wil be detected
    #lower the value, lower computational cost(lower the value more faces will be detected-can give wrong result)
    for (x,y,w,h) in faces:
        cv.rectangle (img,(x,y),(x+w,y+h),(250,180,0),5)
    cv.imshow("Frame",img)
    print(faces)
    print('-'*20)
    if cv.waitKey(1)==27:
        cam.release()
        break

[[135 104 192 192]]
--------------------
[[137 105 192 192]]
--------------------
[[137 105 192 192]]
--------------------
[[135 106 192 192]]
--------------------
[[137 105 192 192]]
--------------------
[[133 105 192 192]]
--------------------
[[133 106 192 192]]
--------------------
[[135 105 192 192]]
--------------------
[[132 103 192 192]]
--------------------
[[135 105 192 192]]
--------------------
[[132 105 192 192]]
--------------------
[[133 105 192 192]]
--------------------
[[134 106 192 192]]
--------------------
[[135 106 192 192]]
--------------------
[[135 105 192 192]]
--------------------
[[132 104 192 192]]
--------------------
[[132 104 192 192]]
--------------------
[[132 104 192 192]]
--------------------
[[139 105 192 192]]
--------------------
[[131 104 192 192]]
--------------------
[[130 105 192 192]]
--------------------
[[131 108 192 192]]
--------------------
[[125 110 192 192]]
--------------------
[[128 110 192 192]]
--------------------
[[133 110 192 19

For crowded places like malls, we'll have to detect multiple faces that will be very small, and for better accuracy, we'll have to detect them all.So there we'll work on different parameters