In [1]:
import cv2 as cv
import numpy as np

In [2]:
classifier=cv.CascadeClassifier("haarcascade_frontalface_default.xml")
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    faces=classifier.detectMultiScale(img,2,2)#img,confidence,neighbours(higher the confidence less faces wil be detected
    #lower the value, lower computational cost(lower the value more faces will be detected-can give wrong result)
    for (x,y,w,h) in faces:
        cv.rectangle (img,(x,y),(x+w,y+h),(250,180,0),5)
        
    cv.imshow("Frame",img)
    # print(faces)
    # print('-'*20)
    if cv.waitKey(1)==27:
        cam.release()
        break

In [3]:
classifier=cv.CascadeClassifier("haarcascade_frontalface_default.xml")
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    faces=classifier.detectMultiScale(img,2,2)#img,confidence,neighbours(higher the confidence less faces wil be detected
    #lower the value, lower computational cost(lower the value more faces will be detected-can give wrong result)
    print(faces)
    for face in faces:
        if face[-1]==max(faces[:,-1]):#if face is of max size it'll braeak the loop
            break
    print(face)
    for (x,y,w,h) in list(faces):
        cv.rectangle (img,(x,y),(x+w,y+h),(250,180,0),5)
        face=img[y:y+h,x:x+w]
        
    cv.imshow("Frame",img)
    cv.imshow('Face',face)
    # print(faces)
    # print('-'*20)
    if cv.waitKey(1)==27:
        cam.release()
        break

[[115 245 192 192]]
[115 245 192 192]
[[120 245 192 192]]
[120 245 192 192]
[[118 244 192 192]]
[118 244 192 192]
[[118 244 192 192]]
[118 244 192 192]
[[118 243 192 192]]
[118 243 192 192]
[[115 243 192 192]]
[115 243 192 192]
[[120 242 192 192]]
[120 242 192 192]
[[120 244 192 192]]
[120 244 192 192]
[[114 243 192 192]]
[114 243 192 192]
[[117 241 192 192]]
[117 241 192 192]
[[115 241 192 192]]
[115 241 192 192]
[[117 242 192 192]]
[117 242 192 192]
[[117 242 192 192]]
[117 242 192 192]
[[119 243 192 192]]
[119 243 192 192]
[[117 241 192 192]]
[117 241 192 192]
[[117 241 192 192]]
[117 241 192 192]
[[115 240 192 192]]
[115 240 192 192]
[[115 240 192 192]]
[115 240 192 192]


In [4]:
img.shape

(480, 640, 3)

In [5]:
max(faces[:,-1])

np.int32(192)

In [6]:
img[y:y+h,x:x+w].shape

(192, 192, 3)

In [7]:
for i in face:
    print(face[0],y,w,h)

[[250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180   0]
 [250 180 

In [8]:
face[0],face[1],face[2],face[3]

(array([[250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],
        [250, 180,   0],


In [9]:
# Load the Haar Cascade Classifier for face detection
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

# Start video capture from the default camera (webcam)
cam = cv.VideoCapture(0)

while True:
    
    # Read one frame from the camera
    _, img = cam.read()
    
    # Flip the frame horizontally (mirror effect)
    img = cv.flip(img, 1)
    
    # Detect faces in the frame (returns list of bounding boxes)
    # Parameters: scaleFactor=1.1, minNeighbors=5
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    # Loop through detected faces
    for f in faces:                             
        if f[-1] == max(faces[:,-1]):           # Choose the face with the largest area (last value = width/height)
            break 

    # If at least one face is detected
    if (len(faces) >= 1):                       
        x = f[0]    # x-coordinate of top-left corner
        y = f[1]    # y-coordinate of top-left corner
        w = f[2]    # width of bounding box
        h = f[3]    # height of bounding box

        # Draw a green rectangle around the detected face
        cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)   
        
        # Crop the face region from the frame
        face = img[y:y+h, x:x+w]
        
        # Resize the cropped face to 256x256 pixels
        face = cv.resize(face, (256,256))

    # Show the full video frame
    cv.imshow('Frame', img)
    
    # Show only the cropped face
    cv.imshow('Face', face)
    
    # Exit when 'Esc' key (27) is pressed
    if cv.waitKey(1) == 27:
        cam.release()  # Release the webcam
        break
